export { FragmentClient } from "./client";

export {
  FragmentError,
  ClientError,
  ConfigurationError,
  ConfigError,
  CookieError,
  FragmentAPIError,
  FragmentPageError,
  UserNotFoundError,
  AlreadySubscribedError,
  AnonymousNumberError,
  TransactionError,
  ConfirmationTimeout,
  SeqnoError,
  ParseError,
  VerificationError,
  OperationError,
  WalletError,
  UnexpectedError,
  fmt,
} from "./exceptions";

export type {
  PreparedTransactionMessage,
  PreparedTransaction,
  EvmInvoice,
  EvmPaymentResult,
  TransactionResult,
  WalletInfo,
  RecipientInfo,
  PurchaseItem,
  PurchaseResult,
  PremiumResult,
  StarsResult,
  AdsTopupResult,
  GiveawayStarsResult,
  GiveawayPremiumResult,
  NftWithdrawalInitResult,
  NftWithdrawalConfirmResult,
  StarsWithdrawalState,
  StarsWithdrawalInitResult,
  StarsWithdrawalConfirmResult,
  BidResult,
  UsernamesResult,
  NumbersResult,
  GiftsResult,
  BidHistoryEntry,
  OwnerHistoryEntry,
  AuctionInfo,
  UsernameInfo,
  NumberInfo,
  GiftAttribute,
  GiftInfo,
  StarsPrice,
  StarsPrices,
  PremiumPriceOption,
  PremiumPrices,
  StarsTransaction,
  PremiumTransaction,
  TopupTransaction,
  ProfileInfo,
  SessionInfo,
  MyBid,
  MyBidsResult,
  MyAsset,
  MyAssetsResult,
  TelegramAccount,
  AssignAccountsResult,
  AssignResult,
  StartAuctionResult,
  NftTransferRecipient,
  NftTransferRequest,
  LoginCodeResult,
  TerminateSessionsResult,
  BatchItemResult,
  BatchResult,
} from "./types/results";

export const VERSION = "1.0.0";